# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mediator.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'mediator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emediator.proto\x12\x08mediator\"F\n\x0bVoiceStream\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x13\n\x0b\x61udio_chunk\x18\x02 \x01(\x0c\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"w\n\x11MediationResponse\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05\x61udio\x18\x03 \x01(\x0c\x12\"\n\x07\x65motion\x18\x04 \x01(\x0e\x32\x11.mediator.Emotion\x12\x0f\n\x07summary\x18\x05 \x01(\t\"\x07\n\x05\x45mpty\"\x19\n\x06Status\x12\x0f\n\x07message\x18\x01 \x01(\t*X\n\x07\x45motion\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04\x43\x41LM\x10\x01\x12\r\n\tASSERTIVE\x10\x02\x12\x0e\n\nEMPATHETIC\x10\x03\x12\t\n\x05\x41NGRY\x10\x04\x12\x0c\n\x08\x43ONFUSED\x10\x05\x32\x7f\n\x0fMediatorService\x12\x41\n\x07Mediate\x12\x15.mediator.VoiceStream\x1a\x1b.mediator.MediationResponse(\x01\x30\x01\x12)\n\x04Ping\x12\x0f.mediator.Empty\x1a\x10.mediator.Statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mediator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMOTION']._serialized_start=257
  _globals['_EMOTION']._serialized_end=345
  _globals['_VOICESTREAM']._serialized_start=28
  _globals['_VOICESTREAM']._serialized_end=98
  _globals['_MEDIATIONRESPONSE']._serialized_start=100
  _globals['_MEDIATIONRESPONSE']._serialized_end=219
  _globals['_EMPTY']._serialized_start=221
  _globals['_EMPTY']._serialized_end=228
  _globals['_STATUS']._serialized_start=230
  _globals['_STATUS']._serialized_end=255
  _globals['_MEDIATORSERVICE']._serialized_start=347
  _globals['_MEDIATORSERVICE']._serialized_end=474
# @@protoc_insertion_point(module_scope)
